
spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true
  application:
    name: "Share Management System"
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:10.1.12.110}:3306/share_management
    username: atmuser
    password: Pas@12345
  flyway:
    baseline-on-migrate : true
    enabled: true
jwt:
  secret: ${SECRET_KEY}
application:
  allowedOrigin:
    - 'http://196.189.90.121:71'
    - 'http://localhost:4200'
  shareValue: 1000
  author: 'Amhara Bank S.c.'
storage:
  location: ""


management:
  endpoints:
    web:
      exposure:
        include: '*'
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

